#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore


class ResourceHandler_3300_5603(ResourceHandler):
    NAME = "Min Range Value"
    DESCRIPTION = '''\
The minimum value that can be measured by the sensor.'''
    DATATYPE = DataType.FLOAT
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        # print value to stdout
        if (instance_id == 0):
            print(0.0)


if __name__ == '__main__':
    ResourceHandler_3300_5603().main()
