#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore


class ResourceHandler_3300_5604(ResourceHandler):
    NAME = "Max Range Value"
    DESCRIPTION = '''\
The maximum value that can be measured by the sensor.'''
    DATATYPE = DataType.FLOAT
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        # print value to stdout
        print(100.0)




if __name__ == '__main__':
    ResourceHandler_3300_5604().main()
