#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore


class ResourceHandler_3300_6042(ResourceHandler):
    NAME = "Measurement Quality Indicator"
    DESCRIPTION = '''\
Measurement quality indicator reported by a smart sensor. 0: UNCHECKED
 * No quality checks were done because they do not exist or can not be
 * applied. 1: REJECTED WITH CERTAINTY The measured value is invalid. 2:
 * REJECTED WITH PROBABILITY The measured value is likely invalid. 3:
 * ACCEPTED BUT SUSPICIOUS The measured value is likely OK. 4: ACCEPTED
 * The measured value is OK. 5-15: Reserved for future extensions. 16-23:
 * Vendor specific measurement quality.'''
    DATATYPE = DataType.INTEGER
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        # TODO: print value to stdout
        print(0)




if __name__ == '__main__':
    ResourceHandler_3300_6042().main()
