#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore


class ResourceHandler_3300_5605(ResourceHandler):
    NAME = "Reset Min and Max Measured Values"
    DESCRIPTION = '''\
Reset the Min and Max Measured Values to Current Value.'''

    def execute(self,
                instance_id,  # int
                args):        # int -> (str or None)
        # TODO: implement
        raise CoapError.NOT_IMPLEMENTED



if __name__ == '__main__':
    ResourceHandler_3300_5605().main()
