#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore


class ResourceHandler_3300_5701(ResourceHandler):
    NAME = "Sensor Units"
    DESCRIPTION = '''\
Measurement Units Definition.'''
    DATATYPE = DataType.STRING
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        if instance_id == 0:
            print("% of maximum charging power")
            return
        elif instance_id == 1:
            print("Planet (0 = Mercury, 1 = Venus, 2 = Earth, 3 = Mars)")
            return
        elif instance_id == 2:
            print("Astronauts number")
            return
        print("No such instance")
        return



if __name__ == '__main__':
    ResourceHandler_3300_5701().main()

