#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore


class ResourceHandler_3300_6050(ResourceHandler):
    NAME = "Fractional Timestamp"
    DESCRIPTION = '''\
Fractional part of the timestamp when sub-second precision is used
 * (e.g., 0.23 for 230 ms).'''
    DATATYPE = DataType.FLOAT
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        # TODO: print value to stdout
        print(0.0)




if __name__ == '__main__':
    ResourceHandler_3300_6050().main()
