#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore


class ResourceHandler_3300_6049(ResourceHandler):
    NAME = "Measurement Quality Level"
    DESCRIPTION = '''\
Measurement quality level reported by a smart sensor. Quality level
 * 100 means that the measurement has fully passed quality check
 * algorithms. Smaller quality levels mean that quality has decreased and
 * the measurement has only partially passed quality check algorithms.
 * The smaller the quality level, the more caution should be used by the
 * application when using the measurement. When the quality level is 0 it
 * means that the measurement should certainly be rejected.'''
    DATATYPE = DataType.INTEGER
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        # TODO: print value to stdout
        print(0)




if __name__ == '__main__':
    ResourceHandler_3300_6049().main()
